Repository DataDog/datadog-sync-cli, pull requests merged in 2024-09, with the labels that each got.

#271 HAMR-179 Add pyproject.toml to fix docker build
  pyproject.toml
Labels: changelog/Fixed

#274 HAMR-179 Build the docker image and push it to github's registry
  .github/workflows/build_publish_docker.yml
Labels: changelog/Added

#276 Update browser test variables ID
  datadog_sync/model/synthetics_tests.py
Labels: changelog/Fixed, mergequeue-status: removed

#277 Specify permissions for workflows.
  .github/workflows/changelog.yml
  .github/workflows/prepare_release.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/test_integrations.yml
Labels: changelog/no-changelog, mergequeue-status: removed

#282 Inject resource context into logs
  datadog_sync/utils/base_resource.py
  datadog_sync/utils/log.py
  datadog_sync/utils/resources_handler.py
  tests/integration/helpers.py
Labels: changelog/Added

#285 Add support for sds group order
  README.md
  datadog_sync/model/sensitive_data_scanner_groups_order.py
  datadog_sync/models/__init__.py
  tests/integration/resources/cassettes/test_sensitive_data_scanner_groups_order/TestSensitiveDataScannerGroupsOrder.test_no_resource_diffs.frozen
  tests/integration/resources/cassettes/test_sensitive_data_scanner_groups_order/TestSensitiveDataScannerGroupsOrder.test_no_resource_diffs.yaml
  tests/integration/resources/cassettes/test_sensitive_data_scanner_groups_order/TestSensitiveDataScannerGroupsOrder.test_resource_cleanup.frozen
  tests/integration/resources/cassettes/test_sensitive_data_scanner_groups_order/TestSensitiveDataScannerGroupsOrder.test_resource_import.frozen
  tests/integration/resources/cassettes/test_sensitive_data_scanner_groups_order/TestSensitiveDataScannerGroupsOrder.test_resource_import.yaml
  tests/integration/resources/cassettes/test_sensitive_data_scanner_groups_order/TestSensitiveDataScannerGroupsOrder.test_resource_sync.frozen
  tests/integration/resources/cassettes/test_sensitive_data_scanner_groups_order/TestSensitiveDataScannerGroupsOrder.test_resource_sync.yaml
  tests/integration/resources/test_sensitive_data_scanner_groups_order.py
Labels: changelog/Added

#284 Add support for SDS resources
  README.md
  datadog_sync/model/sensitive_data_scanner_groups.py
  datadog_sync/model/sensitive_data_scanner_groups_order.py
  datadog_sync/model/sensitive_data_scanner_rules.py
  datadog_sync/models/__init__.py
  scripts/cleanup_org.py
  tests/integration/helpers.py
  tests/integration/resources/cassettes/test_sensitive_data_sanner_groups/TestSensitiveDataScannerGroupsResources.test_no_resource_diffs.frozen
  tests/integration/resources/cassettes/test_sensitive_data_sanner_groups/TestSensitiveDataScannerGroupsResources.test_resource_cleanup.frozen
  tests/integration/resources/cassettes/test_sensitive_data_sanner_groups/TestSensitiveDataScannerGroupsResources.test_resource_cleanup.yaml
  tests/integration/resources/cassettes/test_sensitive_data_sanner_groups/TestSensitiveDataScannerGroupsResources.test_resource_import.frozen
  tests/integration/resources/cassettes/test_sensitive_data_sanner_groups/TestSensitiveDataScannerGroupsResources.test_resource_import.yaml
  tests/integration/resources/cassettes/test_sensitive_data_sanner_groups/TestSensitiveDataScannerGroupsResources.test_resource_sync.frozen
  tests/integration/resources/cassettes/test_sensitive_data_sanner_groups/TestSensitiveDataScannerGroupsResources.test_resource_sync.yaml
  tests/integration/resources/cassettes/test_sensitive_data_sanner_groups/TestSensitiveDataScannerGroupsResources.test_resource_update_sync.frozen
  tests/integration/resources/cassettes/test_sensitive_data_sanner_groups/TestSensitiveDataScannerGroupsResources.test_resource_update_sync.yaml
  tests/integration/resources/cassettes/test_sensitive_data_scanner_groups_order/TestSensitiveDataScannerGroupsOrder.test_no_resource_diffs.frozen
  tests/integration/resources/cassettes/test_sensitive_data_scanner_groups_order/TestSensitiveDataScannerGroupsOrder.test_no_resource_diffs.yaml
  tests/integration/resources/cassettes/test_sensitive_data_scanner_groups_order/TestSensitiveDataScannerGroupsOrder.test_resource_cleanup.frozen
  tests/integration/resources/cassettes/test_sensitive_data_scanner_groups_order/TestSensitiveDataScannerGroupsOrder.test_resource_import.frozen
  tests/integration/resources/cassettes/test_sensitive_data_scanner_groups_order/TestSensitiveDataScannerGroupsOrder.test_resource_import.yaml
  tests/integration/resources/cassettes/test_sensitive_data_scanner_groups_order/TestSensitiveDataScannerGroupsOrder.test_resource_sync.frozen
  tests/integration/resources/cassettes/test_sensitive_data_scanner_groups_order/TestSensitiveDataScannerGroupsOrder.test_resource_sync.yaml
  tests/integration/resources/test_sensitive_data_sanner_groups.py
  tests/integration/resources/test_sensitive_data_sanner_rules.py
  tests/integration/resources/test_sensitive_data_scanner_groups_order.py
Labels: changelog/Added

#270 Add support for logs_archives resource
  README.md
  datadog_sync/model/logs_archives.py
  datadog_sync/model/logs_archives_order.py
  datadog_sync/models/__init__.py
  tests/integration/resources/cassettes/test_logs_archives/TestLogsArchivesResources.test_no_resource_diffs.frozen
  tests/integration/resources/cassettes/test_logs_archives/TestLogsArchivesResources.test_resource_cleanup.frozen
  tests/integration/resources/cassettes/test_logs_archives/TestLogsArchivesResources.test_resource_cleanup.yaml
  tests/integration/resources/cassettes/test_logs_archives/TestLogsArchivesResources.test_resource_import.frozen
  tests/integration/resources/cassettes/test_logs_archives/TestLogsArchivesResources.test_resource_import.yaml
  tests/integration/resources/cassettes/test_logs_archives/TestLogsArchivesResources.test_resource_sync.frozen
  tests/integration/resources/cassettes/test_logs_archives/TestLogsArchivesResources.test_resource_sync.yaml
  tests/integration/resources/cassettes/test_logs_archives/TestLogsArchivesResources.test_resource_update_sync.frozen
  tests/integration/resources/cassettes/test_logs_archives/TestLogsArchivesResources.test_resource_update_sync.yaml
  tests/integration/resources/cassettes/test_logs_archives_order/TestLogsArchivesOrder.test_no_resource_diffs.frozen
  tests/integration/resources/cassettes/test_logs_archives_order/TestLogsArchivesOrder.test_no_resource_diffs.yaml
  tests/integration/resources/cassettes/test_logs_archives_order/TestLogsArchivesOrder.test_resource_cleanup.frozen
  tests/integration/resources/cassettes/test_logs_archives_order/TestLogsArchivesOrder.test_resource_import.frozen
  tests/integration/resources/cassettes/test_logs_archives_order/TestLogsArchivesOrder.test_resource_import.yaml
  tests/integration/resources/cassettes/test_logs_archives_order/TestLogsArchivesOrder.test_resource_sync.frozen
  tests/integration/resources/cassettes/test_logs_archives_order/TestLogsArchivesOrder.test_resource_sync.yaml
  tests/integration/resources/test_logs_archives.py
  tests/integration/resources/test_logs_archives_order.py
Labels: changelog/Added

#283 Adding observability metrics to sync-cli
  .gitignore
  datadog_sync/commands/_import.py
  datadog_sync/commands/shared/options.py
  datadog_sync/constants.py
  datadog_sync/model/notebooks.py
  datadog_sync/utils/base_resource.py
  datadog_sync/utils/configuration.py
  datadog_sync/utils/custom_client.py
  datadog_sync/utils/resources_handler.py
  tests/conftest.py
  tests/integration/helpers.py
  tests/integration/resources/cassettes/test_notebooks/TestNotebooksResources.test_resource_import.yaml
  tests/integration/resources/cassettes/test_restriction_policies/TestRestrictionPoliciesResources.test_resource_import.yaml
Labels: changelog/Added
