Repository DataDog/datadog-sync-cli, pull requests merged in 2025-02, with the labels that each got.

#318 Remove api-clients from CODEOWNERS.
  .github/CODEOWNERS
Labels: changelog/no-changelog, mergequeue-status: rejected

#314 Add pagination support for downtime_schedules
  datadog_sync/model/downtime_schedules.py
  tests/integration/cassettes/test_cli/TestCli.test_import.yaml
  tests/integration/cassettes/test_cli/TestCli.test_import_without_verify_ddr_status.yaml
  tests/integration/cassettes/test_cli/TestCli.test_migrate.yaml
  tests/integration/cassettes/test_cli/TestCli.test_migrate_without_verify_ddr_status.yaml
  tests/integration/resources/cassettes/test_downtime_schedules/TestDowntimeSchedulesResources.test_no_resource_diffs.frozen
  tests/integration/resources/cassettes/test_downtime_schedules/TestDowntimeSchedulesResources.test_no_resource_diffs.yaml
  tests/integration/resources/cassettes/test_downtime_schedules/TestDowntimeSchedulesResources.test_resource_cleanup.frozen
  tests/integration/resources/cassettes/test_downtime_schedules/TestDowntimeSchedulesResources.test_resource_cleanup.yaml
  tests/integration/resources/cassettes/test_downtime_schedules/TestDowntimeSchedulesResources.test_resource_import.frozen
  tests/integration/resources/cassettes/test_downtime_schedules/TestDowntimeSchedulesResources.test_resource_import.yaml
  tests/integration/resources/cassettes/test_downtime_schedules/TestDowntimeSchedulesResources.test_resource_sync.frozen
  tests/integration/resources/cassettes/test_downtime_schedules/TestDowntimeSchedulesResources.test_resource_sync.yaml
  tests/integration/resources/cassettes/test_downtime_schedules/TestDowntimeSchedulesResources.test_resource_update_sync.frozen
  tests/integration/resources/cassettes/test_downtime_schedules/TestDowntimeSchedulesResources.test_resource_update_sync.yaml
Labels: changelog/Fixed

#315 Update warning message when defaulting to EXACT_MATCH_OPERATOR
  datadog_sync/utils/filter.py
Labels: documentation, changelog/no-changelog

#321 The dashboards API has changed, is_read_only is no longer supported
  datadog_sync/model/dashboards.py
  tests/integration/resources/cassettes/test_dashboards/TestDashboardsResources.test_no_resource_diffs.frozen
  tests/integration/resources/cassettes/test_dashboards/TestDashboardsResources.test_no_resource_diffs.yaml
  tests/integration/resources/cassettes/test_dashboards/TestDashboardsResources.test_resource_cleanup.frozen
  tests/integration/resources/cassettes/test_dashboards/TestDashboardsResources.test_resource_cleanup.yaml
  tests/integration/resources/cassettes/test_dashboards/TestDashboardsResources.test_resource_import.frozen
  tests/integration/resources/cassettes/test_dashboards/TestDashboardsResources.test_resource_import.yaml
  tests/integration/resources/cassettes/test_dashboards/TestDashboardsResources.test_resource_sync.frozen
  tests/integration/resources/cassettes/test_dashboards/TestDashboardsResources.test_resource_sync.yaml
  tests/integration/resources/cassettes/test_dashboards/TestDashboardsResources.test_resource_update_sync.frozen
  tests/integration/resources/cassettes/test_dashboards/TestDashboardsResources.test_resource_update_sync.yaml
Labels: changelog/Fixed

#326 Adding more python versions to testing
  setup.cfg
  tox.ini
Labels: changelog/Added
